### ISSUE TITLE
How to preprocess image from .jpg file instead of processed features from edge impulse?

### ISSUE THREAD

**Issue by Ramsonjehu** [ShawnHymel/computer-vision-with-embedded-machine-learning#3]
Hi Team,

I have been using 2.3.1 - CNN Visualizations/ei_saliency_and_grad_cam.ipynb for a while now and its really useful for knowing what my CNN learns. 

As you know, you are using the ground processed features from Edge Impulse. Instead how can I read a .jpg image and preprocess it locally ?

Thanks and Regards,
Ramson Jehu K

**Comment by ShawnHymel** [comment]
You'd have to take a look at what the "Image" block is doing to preprocess the images in your project. In the course (for the electronic components classifier project), I believe the Image block scales the images to 28x28, converts them to grayscale, and normalizes the values so that 0..255 becomes 0.0..1.0.

**Comment by Ramsonjehu** [comment]
![20220104185526934_0](https://user-images.githubusercontent.com/54444543/149091969-b419814d-44a5-41e8-80ac-44aab479a25d.jpg)
This is the image i'm using. This is 1280x720 pixels. My model input is 32x32 rgb data. So resizing is happening and ofcourse as you said, the processed features are normalized values of raw features. 
But how the raw features are extracted from jpeg image? 

This is the raw feature of the image. 

`0xdddfdc, 0xdadcd9, 0xd6d8d5, 0xd4d6d3, 0xd1d3d0, 0xc9cac7, 0xc0c2c0, 0xb9bcbb, 0xb6baba, 0xb2b4b5, 0xabaeaf, 0xa1a5aa, 0x828996, 0x9599a3, 0x777b89, 0x9295a0, 0xa2a6ad, 0xa6aaae, 0xacb1b3, 0xafb3b5, 0xb7b9b8, 0xbfc0be, 0xc2c4c2, 0xc7c9c6, 0xcdcfcc, 0xd1d3d0, 0xd5d7d4, 0xdadcd9, 0xdddfdc, 0xdee0dd, 0xdfe1de, 0xe1e3e0, 0xd3d5d2, 0xcfd1ce, 0xcbcdca, 0xcaccc9, 0xc5c7c4, 0xbcbfbc, 0xb3b6b6, 0xaeb1b1, 0xacb0b1, 0xa8acad, 0xa2a6a8, 0x9a9ea3, 0x777d89, 0x868b94, 0x6a6e7c, 0x868a95, 0x9b9fa4, 0x9da1a4, 0xa3a7a9, 0xa9acac, 0xadb0af, 0xb1b4b3, 0xb8bbb8, 0xbbbdba, 0xbfc1be, 0xc6c8c5, 0xcccecb, 0xced0cd, 0xd3d5d2, 0xd5d7d4, 0xd5d7d4, 0xd5d7d4, 0xcaccc9, 0xc5c7c4, 0xc2c4c1, 0xbfc1be, 0xbabcb9, 0xb3b5b3, 0xa9adae, 0xa6aaaa, 0xa3a6a7, 0x9fa3a4, 0x999d9f, 0x909498, 0x6d737e, 0x7b8086, 0x60646e, 0x80838b, 0x929699, 0x969a9c, 0x9b9fa0, 0x9fa3a2, 0xa5a9a8, 0xa8acab, 0xabaeac, 0xb0b3b0, 0xb5b7b3, 0xb8bab7, 0xbcbebb, 0xc1c3c0, 0xc4c6c3, 0xc7c9c6, 0xc9cbc8, 0xcaccc9, 0xc1c3c0, 0xbcbebb, 0xb9bbb8, 0xb4b6b3, 0xb1b3b0, 0xaaacab, 0xa2a6a6, 0x9ea2a2, 0x9b9fa1, 0x989c9e, 0x919599, 0x888e92, 0x646b74, 0x757980, 0x565a63, 0x787d82, 0x8b8f92, 0x8e9294, 0x959998, 0x999c9c, 0x9b9f9f, 0xa0a3a2, 0xa4a6a4, 0xa6a8a7, 0xa9aca9, 0xaeb1ad, 0xb1b3b0, 0xb4b6b3, 0xb7b9b6, 0xb9bbb8, 0xbabcb9, 0xbcbebb, 0xb7b9b6, 0xb3b5b2, 0xb0b2af, 0xaeb0ad, 0xaaaca9, 0xa2a4a3, 0x9b9e9f, 0x969a9b, 0x969b9c, 0x929798, 0x8c9295, 0x82888d, 0x5c646d, 0x6c7178, 0x50545d, 0x73787d, 0x878b8e, 0x898d90, 0x8d9092, 0x929595, 0x949899, 0x979b9b, 0x9b9e9d, 0x9ea2a1, 0xa0a3a2, 0xa4a6a4, 0xa8aba8, 0xaaada9, 0xabaeaa, 0xaeb0ad, 0xaeb1ae, 0xafb1ae, 0xb0b2af, 0xacaeab, 0xabadaa, 0xaaaca9, 0xa3a6a3, 0x9c9f9e, 0x949899, 0x909597, 0x909596, 0x8d9192, 0x888d8f, 0x7a8285, 0x596069, 0x6f757a, 0x4a4e56, 0x74787d, 0x838789, 0x84898b, 0x888d8f, 0x898f8f, 0x8c9291, 0x919696, 0x929696, 0x959999, 0x9a9d9c, 0x9b9e9d, 0x9ca09e, 0xa1a4a0, 0xa4a6a3, 0xa5a7a4, 0xa6a8a5, 0xa7a9a6, 0xa7a9a6, 0xa3a5a2, 0xa3a5a2, 0x9ea09e, 0x999d9b, 0x939897, 0x8e9193, 0x8a8f90, 0x868d8d, 0x828a89, 0x7d8485, 0x757b7e, 0x575d64, 0x787b7e, 0x43474d, 0x6d7173, 0x858888, 0x818685, 0x838888, 0x868a8a, 0x868c8b, 0x898f8d, 0x8e9292, 0x8e9393, 0x909494, 0x959998, 0x979b99, 0x989c9a, 0x9da09d, 0x9fa29e, 0x9ea19e, 0xa0a29f, 0x9d9f9c, 0x9b9d9a, 0x989a97, 0x949795, 0x929693, 0x8e9191, 0x898d8d, 0x838a8a, 0x828889, 0x818584, 0x7e8282, 0x777a7b, 0x53545a, 0x676769, 0x484549, 0x605e5f, 0x888986, 0x7c7e7c, 0x818482, 0x818483, 0x858786, 0x858986, 0x868a89, 0x898d8c, 0x8a8e8e, 0x8c9090, 0x919492, 0x919491, 0x939693, 0x989a97, 0x999b98, 0x999b98, 0x969895, 0x949693, 0x919491, 0x8f918f, 0x8b8f8e, 0x898d8b, 0x858a88, 0x818684, 0x808383, 0x808280, 0x7e807d, 0x737574, 0x555056, 0x656264, 0x4d4349, 0x645d60, 0x747272, 0x787977, 0x7d7e7b, 0x7f807e, 0x7f817f, 0x828482, 0x848683, 0x848784, 0x878987, 0x878c8a, 0x888d8a, 0x8b908e, 0x8d918e, 0x8f918e, 0x909390, 0x929491, 0x8f918e, 0x8d908d, 0x888d8b, 0x858a88, 0x838886, 0x828482, 0x80827f, 0x80827e, 0x80827f, 0x7f807e, 0x7b7c79, 0x737473, 0x554f54, 0x615d5f, 0x4a3f44, 0x635d60, 0x6e6d6e, 0x716f6f, 0x757573, 0x787977, 0x7b7c79, 0x7d7e7c, 0x7f817e, 0x80827f, 0x828481, 0x868885, 0x868a87, 0x868a87, 0x888c89, 0x8b8d8a, 0x8b8c89, 0x8c8e8b, 0x888a87, 0x878986, 0x868985, 0x858984, 0x848683, 0x828380, 0x7e7f7c, 0x797b79, 0x727473, 0x696a6b, 0x5c5c5d, 0x4f4d51, 0x4a454b, 0x5c585b, 0x443b42, 0x605b5d, 0x6d6d6d, 0x6b6a6b, 0x6e6e6d, 0x727271, 0x757875, 0x787a77, 0x787a77, 0x7c7e7b, 0x7d7f7c, 0x80827f, 0x848683, 0x828784, 0x838684, 0x858885, 0x868986, 0x868885, 0x8a8b88, 0x878b89, 0x848a87, 0x7c8180, 0x717474, 0x646566, 0x515355, 0x434246, 0x38353a, 0x302b31, 0x2f272d, 0x2f272e, 0x3c363b, 0x595658, 0x3d363d, 0x545153, 0x636362, 0x696968, 0x6f716f, 0x757673, 0x767875, 0x787a77, 0x767876, 0x767876, 0x7a7c79, 0x7d7f7c, 0x7f817e, 0x818481, 0x7f8480, 0x7f8480, 0x828481, 0x818380, 0x737a7c, 0x61696d, 0x4d5358, 0x3a3f43, 0x2f2e33, 0x2a262b, 0x292529, 0x312c2f, 0x383336, 0x3d3a3d, 0x413e41, 0x413e42, 0x454347, 0x4a484b, 0x4d4a4e, 0x464447, 0x3f3d40, 0x403f43, 0x474748, 0x565756, 0x666866, 0x757774, 0x7d7f7b, 0x7f817e, 0x7d7f7c, 0x7e807d, 0x7d7f7c, 0x7e807d, 0x7e817e, 0x7d807d, 0x7c7f7c, 0x7d807c, 0x262a2f, 0x1f2124, 0x252225, 0x312c2f, 0x3f3a3d, 0x474448, 0x4b4a4c, 0x4b4a4d, 0x49494d, 0x4d4e51, 0x565659, 0x606164, 0x6e7071, 0x7e8181, 0x8c8f8e, 0x878a88, 0x7a7d7d, 0x6a6c6e, 0x606062, 0x4f4f52, 0x424145, 0x404143, 0x4b4c4c, 0x606160, 0x727471, 0x797b78, 0x7f817e, 0x80827f, 0x80827f, 0x7f817e, 0x7c7f7b, 0x7a7e7b, 0x3a3b3b, 0x4d4e4d, 0x555657, 0x555656, 0x4f5252, 0x505254, 0x595b5d, 0x6a6d6e, 0x7f8282, 0x8f9391, 0x999d9a, 0x9ca09e, 0x9ba09d, 0x999e9b, 0x969b99, 0x989d9b, 0x9b9f9d, 0x9da19f, 0x9fa39f, 0x9c9f9c, 0x929491, 0x7d7f7d, 0x626564, 0x505154, 0x444649, 0x46484a, 0x585a5a, 0x6a6c6b, 0x777977, 0x7f817e, 0x808380, 0x7e817e, 0x5c5e5c, 0x5a5c5c, 0x606164, 0x6c6e6e, 0x808382, 0x939895, 0xa0a4a1, 0xa6aaa7, 0xa6a9a6, 0xa3a7a3, 0xa2a5a1, 0xa3a5a2, 0xa2a6a2, 0xa0a5a2, 0xa0a5a1, 0x9fa4a0, 0x9fa3a0, 0x9ea29f, 0x9fa29f, 0xa0a29f, 0xa2a5a1, 0xa5a9a5, 0xa6aaa7, 0xa2a4a1, 0x949693, 0x7b7c7d, 0x5e6061, 0x4e5153, 0x494c4f, 0x555757, 0x676967, 0x757775, 0x7e817f, 0x979997, 0xa7a9a6, 0xacafab, 0xaeb0ac, 0xacafab, 0xaaaca9, 0xa9aca8, 0xaaaca9, 0xaaaca9, 0xa9aba8, 0xaaaca9, 0xaaaca9, 0xaaaca9, 0xa9aba8, 0xa9aca8, 0xa9aca8, 0xa9aba8, 0xaaaca9, 0xa8aaa7, 0xa6a9a6, 0xa5a7a4, 0xa4a6a3, 0xa5a7a4, 0xa8aaa7, 0xabada9, 0xa7aaa6, 0x9a9c99, 0x878887, 0x6e6f6f, 0x5a5d5d, 0x575c5b, 0xb0b2af, 0xafb1ae, 0xadafab, 0xadafac, 0xaeb0ad, 0xb1b3b0, 0xb1b3b0, 0xb1b3b0, 0xb1b3b0, 0xb0b2af, 0xafb2af, 0xb0b3b0, 0xb2b4b1, 0xb3b5b2, 0xb2b4b1, 0xb2b4b1, 0xb1b3b0, 0xb1b3b0, 0xafb1ae, 0xaeb0ad, 0xadafac, 0xacaeab, 0xabadaa, 0xaaaca9, 0xa9aba8, 0xa8aaa7, 0xa8aaa7, 0xaaaca9, 0xacaeab, 0xacaeab, 0xa5a6a3, 0x9a9d9a, 0xb2b4b1, 0xb4b6b3, 0xb5b7b4, 0xb5b7b4, 0xb7b9b6, 0xb6b8b5, 0xb4b6b3, 0xb4b7b3, 0xb5b7b4, 0xb7b9b6, 0xb9bbb8, 0xb9bbb8, 0xb9bbb8, 0xbabcb9, 0xb9bbb8, 0xb8bab7, 0xb7b9b6, 0xb4b6b3, 0xb3b5b2, 0xb3b5b2, 0xb2b4b1, 0xb1b3b0, 0xb0b2af, 0xafb1ae, 0xaeb0ad, 0xadafac, 0xacaeab, 0xacaeab, 0xa9aba8, 0xa7a9a6, 0xa7a9a6, 0xaaaca9, 0xb9bbb8, 0xb9bbb8, 0xb9bbb8, 0xb9bbb8, 0xbbbdba, 0xbbbdba, 0xbcbebb, 0xbfc0be, 0xbfc1be, 0xc0c2bf, 0xc0c2bf, 0xc0c2bf, 0xbfc1be, 0xbec0bd, 0xbbbdbb, 0xbabcb9, 0xbabcb9, 0xb9bbb8, 0xb7b9b6, 0xb6b8b5, 0xb6b8b5, 0xb9bbb8, 0xb5b7b4, 0xb3b5b2, 0xb2b4b1, 0xb1b3b0, 0xb0b2af, 0xb0b2af, 0xadafac, 0xacaeab, 0xaaaca9, 0xa9aba8, 0xb7b9b6, 0xbabcb9, 0xbdbfbc, 0xc0c2bf, 0xc2c4c1, 0xc4c6c3, 0xc6c8c5, 0xc5c7c4, 0xc4c6c3, 0xc5c7c4, 0xc5c7c4, 0xc3c5c2, 0xc1c3c0, 0xbfc1be, 0xbfc1be, 0xc2c4c1, 0xc0c2bf, 0xbec0bd, 0xbdbfbc, 0xbcbebb, 0xbcbebb, 0xbcbebb, 0xbabcb9, 0xb8bab7, 0xb5b7b4, 0xb3b5b2, 0xb2b4b1, 0xb1b3b0, 0xb1b3b0, 0xb0b2af, 0xadafac, 0xacaeab, 0xbdbfbc, 0xbec0bd, 0xc0c2bf, 0xc7c9c6, 0xcaccc9, 0xcaccc9, 0xc9cbc8, 0xc7c9c6, 0xc9cbc8, 0xc9cbc8, 0xc9cbc8, 0xc8cac7, 0xc6c8c5, 0xc5c7c4, 0xc6c8c5, 0xc6c8c5, 0xc4c6c3, 0xc2c4c1, 0xc1c3c0, 0xc0c2bf, 0xbfc1be, 0xbec0bd, 0xbec0bd, 0xbdbfbc, 0xbabcb9, 0xb8bab7, 0xb4b6b3, 0xb5b7b4, 0xb4b6b3, 0xb2b4b1, 0xb1b3b0, 0xaeb0ad, 0xc4c6c3, 0xc3c5c2, 0xcbcdca, 0xcbcdca, 0xcbcdca, 0xcdcfcc, 0xcccecb, 0xcbcdca, 0xcaccc9, 0xcaccc9, 0xcaccc9, 0xcaccc9, 0xcaccc9, 0xcaccc9, 0xcccecb, 0xc9cbc8, 0xc8cac7, 0xc7c9c6, 0xc5c7c4, 0xc4c6c3, 0xc4c6c3, 0xc3c5c2, 0xc2c4c1, 0xc0c2bf, 0xbdbfbc, 0xbbbdba, 0xbabcb9, 0xb6b8b5, 0xb5b7b4, 0xb4b6b3, 0xb4b6b3, 0xb2b4b1, 0xc6c8c5, 0xc7c9c6, 0xcbcdca, 0xcbcdca, 0xcdcfcc, 0xd0d2cf, 0xced0cd, 0xced0cd, 0xcdcfcc, 0xcdcfcc, 0xcccecb, 0xcbcdca, 0xcccecb, 0xcdcfcc, 0xcdcfcc, 0xcdcfcc, 0xcdcfcc, 0xcaccc9, 0xc8cac7, 0xcaccc9, 0xc9cbc8, 0xc7c9c6, 0xc6c8c5, 0xc4c6c3, 0xc1c3c0, 0xc0c2bf, 0xbdbfbc, 0xbabcb9, 0xb8bab7, 0xb7b9b6, 0xb7b9b6, 0xb4b6b3, 0xc8cac7, 0xc8cac7, 0xcdcfcc, 0xd0d2cf, 0xd1d3d0, 0xd0d2cf, 0xd0d2cf, 0xd2d4d1, 0xd2d4d1, 0xd3d5d2, 0xd3d5d2, 0xd0d2cf, 0xcfd1ce, 0xced0cd, 0xd0d2cf, 0xd1d3d0, 0xcfd1ce, 0xcdcfcc, 0xcbcdca, 0xcbcdca, 0xcbcdca, 0xcaccc9, 0xc9cbc8, 0xc8cac7, 0xc6c8c5, 0xc3c5c2, 0xc1c3c0, 0xbec0bd, 0xbcbebb, 0xbabcb9, 0xb8bab7, 0xb7b9b6, 0xcaccc9, 0xcdcfcc, 0xd1d3d0, 0xd3d5d2, 0xd1d3d0, 0xd1d3d0, 0xd3d5d2, 0xd5d7d4, 0xd4d6d3, 0xd5d7d4, 0xd7d9d6, 0xd4d6d3, 0xd3d5d2, 0xd3d5d2, 0xd2d4d1, 0xd2d4d1, 0xd1d3d0, 0xd1d3d0, 0xd1d3d0, 0xcfd1ce, 0xcdcfcc, 0xcbcdca, 0xcaccc9, 0xc9cbc8, 0xc7c9c6, 0xc6c8c5, 0xc4c6c3, 0xc1c3c0, 0xbec0bd, 0xbcbebb, 0xbabcb9, 0xb9bbb8, 0xcdcfcc, 0xd0d2cf, 0xd3d5d2, 0xd4d6d3, 0xd3d5d2, 0xd3d5d2, 0xd4d6d3, 0xd7d9d6, 0xd7d9d6, 0xd7d9d6, 0xd8dad7, 0xdadcd9, 0xdbddda, 0xd7d9d6, 0xd5d7d4, 0xd4d6d3, 0xd3d5d2, 0xd2d4d1, 0xd4d6d3, 0xd2d4d1, 0xcfd1ce, 0xced0cd, 0xcccecb, 0xcdcfcc, 0xcbcdca, 0xc9cbc8, 0xc6c8c5, 0xc4c6c3, 0xc2c4c1, 0xbfc1be, 0xbdbfbc, 0xbbbdba, 0xcfd1ce, 0xd3d5d2, 0xd4d6d3, 0xd5d7d4, 0xd6d8d5, 0xd6d8d5, 0xd9dbd8, 0xdadcd9, 0xd9dbd8, 0xd8dad7, 0xdadcd9, 0xdbddda, 0xdadcd9, 0xdadcd9, 0xd9dbd8, 0xd7d9d6, 0xd4d6d3, 0xd4d6d3, 0xd6d8d5, 0xd5d7d4, 0xd3d5d2, 0xd2d4d1, 0xd0d2cf, 0xd1d3d0, 0xcdcfcc, 0xcbcdca, 0xcaccc9, 0xc7c9c6, 0xc3c5c2, 0xc2c4c1, 0xc1c3c0, 0xbfc1be, 0xd2d4d1, 0xd4d6d3, 0xd6d8d5, 0xd9dbd8, 0xd9dbd8, 0xd9dbd8, 0xdadcd9, 0xdddfdc, 0xdddfdc, 0xdbddda, 0xdcdedb, 0xdcdedc, 0xdcded9, 0xdddfdb, 0xdcdeda, 0xdbddda, 0xd9dbd8, 0xd9dbd8, 0xdcdedb, 0xd9dbd8, 0xd6d8d5, 0xd5d7d4, 0xd3d5d2, 0xd3d5d2, 0xd0d2cf, 0xced0cd, 0xcccecb, 0xc8cac7, 0xc7c9c6, 0xc5c7c4, 0xc5c7c4, 0xc1c3c0, 0xd3d5d2, 0xd5d7d4, 0xd7d9d6, 0xd7d9d6, 0xdbddda, 0xdbddda, 0xdadcd9, 0xdee0dd, 0xdee0dd, 0xdee0dd, 0xdfe1de, 0xdfe1de, 0xe1e3e0, 0xe2e4e1, 0xe1e3df, 0xdee0dd, 0xe0e2df, 0xdddfdc, 0xdadcd9, 0xd9dbd8, 0xd9dbd8, 0xd7d9d6, 0xd5d7d4, 0xd4d6d3, 0xd3d5d2, 0xd0d2cf, 0xced0cd, 0xcccecb, 0xcaccc9, 0xc8cac7, 0xc6c8c5, 0xc3c5c2, 0xd4d6d3, 0xd6d8d5, 0xd8dad7, 0xd9dbd8, 0xdcdedb, 0xdcdedb, 0xdddfdc, 0xe0e2de, 0xe2e4e1, 0xe3e5e2, 0xe5e7e4, 0xe6e8e5, 0xe4e6e2, 0xe3e5e1, 0xe5e7e3, 0xe5e7e3, 0xe2e4e1, 0xdee0dc, 0xdee0dd, 0xdddfda, 0xdbddda, 0xdadcd9, 0xd8dad6, 0xd6d8d5, 0xd4d6d3, 0xd3d5d2, 0xd1d3d0, 0xcdcfcc, 0xcdcfcc, 0xcbcdca, 0xc8cac7, 0xc3c5c2, 0xd6d8d5, 0xdbddda, 0xdcdedb, 0xdee0dd, 0xe0e2df, 0xe1e3df, 0xe2e4e1, 0xe2e4e0, 0xe3e5e1, 0xe6e8e4, 0xe8eae6, 0xebede9, 0xe9ebe7, 0xe9ebe6, 0xe9ebe8, 0xe8eae6, 0xe4e6e2, 0xe2e4e0, 0xe4e6e2, 0xe1e3e0, 0xdee0dd, 0xdcdedb, 0xdbddda, 0xd8dad7, 0xd6d8d5, 0xd5d7d4, 0xd3d5d2, 0xd2d4d1, 0xd0d2cf, 0xced0cd, 0xcbcdca, 0xc6c8c5`

I tried using opencv to read the image and resize to 32 pixels using the following code. 

```
img1 = cv2.imread('20220104185526934_0.jpg')
resized_img= cv2.resize(img1, (32, 32))
```

But the values in resized img and raw features are not same. How to generate raw features from jpeg?

**Comment by ShawnHymel** [comment]
From what I gathered, Edge Impulse uses the Lanczos algorithm for interpolation when resizing images. I can't get exactly the features that are produced in their studio, but the following snippet gets me very close:

```
import cv2

file_path = "/content/49_6.png.2gravukk.png"

# Desired resolution of images
TARGET_WIDTH = 28
TARGET_HEIGHT = 28

# Read image and covert to features
img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)
resized_img = cv2.resize(img, (TARGET_WIDTH, TARGET_HEIGHT), interpolation=cv2.INTER_LANCZOS4) / 255
```

**Comment by Ramsonjehu** [comment]
Hi,
I'm seeing this LANCZOS4 interpolation for the first time. I have tried to replicate the features using other interpolations like NEAREST, AREA, etc. 
Thank you so much Shawn. I will give it a try. 
 
Regards,
Ramson Jehu K
